[package]
name = "qbit-cleanup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.22"
qbit-rs = "0.4"
tokio = { version = "1.42", features = ["full"] }
url = "2.5"
